header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors

  paths:
    - '**/*.go'
    - '**/*.s'

  comment: on-failure

checking:
  spelling:
    ignore-words:
      - Invokable
      - invokable
      - InvokableLambda
      - InvokableRun
      - outter
      - Opion
      - TOpion
      - renderring