# Typo check: https://github.com/crate-ci/typos
[default]
# 添加需要忽略的单词
exclude-words = [
    "Invokable",
    "invokable",
    "InvokableLambda",
    "InvokableRun",
    "outter",
    "Opion",
    "TOpion",
    "renderring",
]

[files]
extend-exclude = ["go.mod", "go.sum", "check_branch_name.sh"]
